### ISSUE TITLE
KeyError: "

### ISSUE THREAD

**Issue by ChosunOne** [ivan-vasilev/Python-Deep-Learning-SE#3] opened 2019-02-09 08:20 UTC
https://github.com/ivan-vasilev/Python-Deep-Learning-SE/blob/53ee58399c2352e12265a82be274e6ba61f33cce/ch07/language%20model/model.py#L212

The character " produces a key error in the example.  The double quote should be replaced with the “ and ” characters to rectify this error.

**Comment by ivan-vasilev** [comment] 2019-02-09 13:14
I've been unable to reproduce this issue. Nevertheless, I've escaped " with \" (although I'm not sure whether this would fix it either).

**Comment by ChosunOne** [comment] 2019-02-09 15:56
That seems to have done the trick for me.  Thanks!

**Comment by ChosunOne** [comment] 2019-02-09 15:59
Reopening because the issues persists:
```
char_list:  106 ['\n', '\r', ' ', '!', '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'À', 'Á', 'É', 'à', 'á', 'â', 'ä', 'æ', 'ç', 'è', 'é', 'ê', 'ë', 'í', 'î', 'ï', 'ó', 'ô', 'ö', 'ú', 'ü', 'ý', 'œ', '—', '‘', '’', '“', '”', '\ufeff']
char_dict:  {'\n': 0, '\r': 1, ' ': 2, '!': 3, '(': 4, ')': 5, '*': 6, ',': 7, '-': 8, '.': 9, '/': 10, '0': 11, '1': 12, '2': 13, '3': 14, '4': 15, '5': 16, '6': 17, '7': 18, '8': 19, '9': 20, ':': 21, ';': 22, '=': 23, '?': 24, 'A': 25, 'B': 26, 'C': 27, 'D': 28, 'E': 29, 'F': 30, 'G': 31, 'H': 32, 'I': 33, 'J': 34, 'K': 35, 'L': 36, 'M': 37, 'N': 38, 'O': 39, 'P': 40, 'Q': 41, 'R': 42, 'S': 43, 'T': 44, 'U': 45, 'V': 46, 'W': 47, 'X': 48, 'Y': 49, 'Z': 50, 'a': 51, 'b': 52, 'c': 53, 'd': 54, 'e': 55, 'f': 56, 'g': 57, 'h': 58, 'i': 59, 'j': 60, 'k': 61, 'l': 62, 'm': 63, 'n': 64, 'o': 65, 'p': 66, 'q': 67, 'r': 68, 's': 69, 't': 70, 'u': 71, 'v': 72, 'w': 73, 'x': 74, 'y': 75, 'z': 76, 'À': 77, 'Á': 78, 'É': 79, 'à': 80, 'á': 81, 'â': 82, 'ä': 83, 'æ': 84, 'ç': 85, 'è': 86, 'é': 87, 'ê': 88, 'ë': 89, 'í': 90, 'î': 91, 'ï': 92, 'ó': 93, 'ô': 94, 'ö': 95, 'ú': 96, 'ü': 97, 'ý': 98, 'œ': 99, '—': 100, '‘': 101, '’': 102, '“': 103, '”': 104, '\ufeff': 105}
labels:  ['\n', '\r', ' ', '!', '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'À', 'Á', 'É', 'à', 'á', 'â', 'ä', 'æ', 'ç', 'è', 'é', 'ê', 'ë', 'í', 'î', 'ï', 'ó', 'ô', 'ö', 'ú', 'ü', 'ý', 'œ', '—', '‘', '’', '“', '”', '\ufeff']
```


```Sample 5:
prime_string:  "If only you knew,"
Traceback (most recent call last):
  File "/home/chosunone/source/tf_lstm_war_and_peace/model.py", line 232, in <module>
    main()
  File "/home/chosunone/source/tf_lstm_war_and_peace/model.py", line 223, in main
    train_and_sample(500, restore=False)
  File "/home/chosunone/source/tf_lstm_war_and_peace/model.py", line 213, in train_and_sample
    sample_length=500)
  File "/home/chosunone/source/tf_lstm_war_and_peace/model.py", line 98, in sample
    character_idx = self.label_map[character]
KeyError: '"'
```

It seems that the original text doesn't contain the standard " symbol when acquired from:
[Project Gutenberg .txt](http://www.gutenberg.org/ebooks/2600)

**Comment by ivan-vasilev** [comment] 2019-02-09 21:27
Thank you for your contribution. It is now merged in the master branch.

**Closed as completed by ivan-vasilev** 2019-02-09 21:27 UTC
